sudo: false
language: java
install: true
jdk:
  - openjdk8
  - openjdk9
  #- openjdk12
addons:
  sonarcloud:
    organization: "wherkamp-github"
    token: $SONAR_TOKEN
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE test;'
